### ISSUE TITLE
Can't access web page

### ISSUE THREAD

**Issue by morfeo9950** [medaboub/mqtt-chat-android-demo#1]
Is the project still active?, can't access web page for register or login, documentation web page is working but not for register new user.

**Comment by medaboub** [comment]
Yes still active. this is the r[egister link](https://mqtt-chat.com/account/register).

**Comment by morfeo9950** [comment]
The link you paste in your answer is not working, it says error 500, not working in firefox and not working on edge.

**Comment by medaboub** [comment]
it's working right now. from what country you try to access.?

**Comment by morfeo9950** [comment]
Im from Argentina, got blank page on Firefox and error 500 on Edge, not tested on Chrome, i dont have any blocker on browsers nor vpn.
